ALTER TYPE "ReferralStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "coins" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Referral"
ADD COLUMN IF NOT EXISTS "rewardCoins" INTEGER NOT NULL DEFAULT 0;
