-- CreateTable
CREATE TABLE "MonetizationSettings" (
    "id" TEXT NOT NULL,
    "freeChapters" INTEGER NOT NULL DEFAULT 3,
    "paidFrom" INTEGER NOT NULL DEFAULT 4,
    "autoLock" BOOLEAN NOT NULL DEFAULT true,
    "schedUnlock" BOOLEAN NOT NULL DEFAULT false,
    "schedUnlockFrequency" TEXT NOT NULL DEFAULT 'Weekly',
    "chapterUnlockCost" INTEGER NOT NULL DEFAULT 10,
    "audiobookUnlockCost" INTEGER NOT NULL DEFAULT 25,
    "referralRewardCoins" INTEGER NOT NULL DEFAULT 100,
    "dailyStreakReward" INTEGER NOT NULL DEFAULT 5,
    "adWatchReward" INTEGER NOT NULL DEFAULT 3,
    "welcomeBonusCoins" INTEGER NOT NULL DEFAULT 50,
    "freeReadLimit" INTEGER NOT NULL DEFAULT 20,
    "subUnlimited" BOOLEAN NOT NULL DEFAULT true,
    "aiPremiumOnly" BOOLEAN NOT NULL DEFAULT true,
    "offlinePremiumOnly" BOOLEAN NOT NULL DEFAULT true,
    "publicDomainFree" BOOLEAN NOT NULL DEFAULT true,
    "subOnlyBooks" BOOLEAN NOT NULL DEFAULT false,
    "earlyAccess" BOOLEAN NOT NULL DEFAULT false,
    "earlyAccessHours" INTEGER NOT NULL DEFAULT 24,
    "writerRevenueShare" INTEGER NOT NULL DEFAULT 70,
    "minPayoutThreshold" DOUBLE PRECISION NOT NULL DEFAULT 20,
    "payoutSchedule" TEXT NOT NULL DEFAULT 'Monthly',
    "perfBonusThreshold" DOUBLE PRECISION NOT NULL DEFAULT 500,
    "perfBonusAmount" DOUBLE PRECISION NOT NULL DEFAULT 50,
    "minPublishedChapters" INTEGER NOT NULL DEFAULT 5,
    "minReadCount" INTEGER NOT NULL DEFAULT 500,
    "requireIdVerify" BOOLEAN NOT NULL DEFAULT true,
    "requireTaxInfo" BOOLEAN NOT NULL DEFAULT true,
    "newWriterProbationDays" INTEGER NOT NULL DEFAULT 30,
    "coinSystemEnabled" BOOLEAN NOT NULL DEFAULT true,
    "subscriptionsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "referralProgramEnabled" BOOLEAN NOT NULL DEFAULT true,
    "adRewardEnabled" BOOLEAN NOT NULL DEFAULT true,
    "writerPayoutsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "monetizationMaintMode" BOOLEAN NOT NULL DEFAULT false,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MonetizationSettings_pkey" PRIMARY KEY ("id")
);